# Generated by Django 5.1.3 on 2024-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='marquee/')),
            ],
        ),
    ]
