# Generated by Django 5.1.3 on 2024-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('order', models.IntegerField(unique=True, verbose_name='Ordem')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='machines/', verbose_name='Imagem')),
                ('inStock', models.BooleanField(default=True, verbose_name='Em Stock')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(upload_to='marquee/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.IntegerField(unique=True, verbose_name='Ordem'),
        ),
    ]
