# Generated by Django 5.1.3 on 2024-11-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_machine_image_machine_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='inStock',
        ),
    ]
